require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Rails:
  Enabled: false

# Lint/AmbiguousOperator:
# Lint/AmbiguousRegexpLiteral:
# Lint/AssignmentInCondition:
# Lint/BlockAlignment:
# Lint/CircularArgumentReference:
# Lint/ConditionPosition:
# Lint/Debugger:
# Lint/DefEndAlignment:
# Lint/DeprecatedClassMethods:
# Lint/DuplicatedKey:
# Lint/DuplicateMethods:
# Lint/EachWithObjectArgument:
# Lint/ElseLayout:
# Lint/EmptyEnsure:
# Lint/EmptyInterpolation:
# Lint/EndAlignment:
# Lint/EndInMethod:
# Lint/EnsureReturn:
# Lint/Eval:
# Lint/FloatOutOfRange:
# Lint/FormatParameterMismatch:
# Lint/HandleExceptions:
# Lint/ImplicitStringConcatenation:
# Lint/IneffectiveAccessModifier:
# Lint/InvalidCharacterLiteral:
# Lint/LiteralInCondition:
# Lint/LiteralInInterpolation:
# Lint/Loop:
# Lint/NestedMethodDefinition:
# Lint/NextWithoutAccumulator:
# Lint/ParenthesesAsGroupedExpression:
# Lint/RandOne:
# Lint/RequireParentheses:
# Lint/RescueException:
# Lint/ShadowingOuterLocalVariable:
# Lint/StringConversionInInterpolation:
# Lint/UnderscorePrefixedVariableName:
# Lint/UnneededDisable:
# Lint/UnreachableCode:
# Lint/UnusedBlockArgument:
# Lint/UnusedMethodArgument:
# Lint/UselessAccessModifier:
# Lint/UselessAssignment:
# Lint/UselessComparison:
# Lint/UselessElseWithoutRescue:
# Lint/UselessSetterCall:
# Lint/Void:
# Metrics/AbcSize:
# Metrics/BlockNesting:
# Metrics/ClassLength:
# Metrics/CyclomaticComplexity:
Metrics/LineLength:
  Enabled: true
  Max: 120
Metrics/MethodLength:
  Enabled: true
  Max: 12
# Metrics/ModuleLength:
# Metrics/ParameterLists:
# Metrics/PerceivedComplexity:
# Performance/Casecmp:
# Performance/DoubleStartEndWith:
# Performance/EndWith:
# Performance/LstripRstrip:
# Performance/RangeInclude:
# Performance/RedundantBlockCall:
# Performance/RedundantMatch:
# Performance/RedundantMerge:
# Performance/RedundantSortBy:
# Performance/StartWith:
# Performance/StringReplacement:
# Performance/TimesMap:
# Rails/ActionFilter:
# Rails/Date:
# Rails/Delegate:
# Rails/FindBy:
# Rails/FindEach:
# Rails/HasAndBelongsToMany:
# Rails/Output:
# Rails/PluralizationGrammar:
# Rails/ReadWriteAttribute:
# Rails/ScopeArgs:
# Rails/TimeZone:
# Rails/UniqBeforePluck:
# Rails/Validation:
# RSpec/AnyInstance:
# RSpec/DescribeClass:
# RSpec/DescribedClass:
# RSpec/DescribeMethod:
# RSpec/ExampleLength:
# RSpec/ExampleWording:
# RSpec/FilePath:
# RSpec/Focus:
# RSpec/InstanceVariable:
# RSpec/MultipleDescribes:
# RSpec/NotToNot:
# RSpec/VerifiedDoubles:
# Style/AccessModifierIndentation:
# Style/AccessorMethodName:
# Style/Alias:
# Style/AlignArray:
# Style/AlignHash:
# Style/AlignParameters:
# Style/AndOr:
# Style/ArrayJoin:
# Style/AsciiComments:
# Style/AsciiIdentifiers:
# Style/Attr:
# Style/BarePercentLiterals:
# Style/BeginBlock:
# Style/BlockComments:
# Style/BlockDelimiters:
# Style/BlockEndNewline:
# Style/BracesAroundHashParameters:
# Style/CaseEquality:
# Style/CaseIndentation:
# Style/CharacterLiteral:
# Style/ClassAndModuleCamelCase:
# Style/ClassAndModuleChildren:
# Style/ClassCheck:
# Style/ClassMethods:
# Style/ClassVars:
# Style/ColonMethodCall:
# Style/CommentAnnotation:
# Style/CommentIndentation:
# Style/ConditionalAssignment:
# Style/ConstantName:
# Style/DefWithParentheses:
# Style/DeprecatedHashMethods:
Style/Documentation:
  Enabled: false
# Style/DotPosition:
# Style/DoubleNegation:
# Style/EachWithObject:
# Style/ElseAlignment:
# Style/EmptyElse:
# Style/EmptyLineBetweenDefs:
# Style/EmptyLines:
# Style/EmptyLinesAroundAccessModifier:
# Style/EmptyLinesAroundBlockBody:
# Style/EmptyLinesAroundClassBody:
# Style/EmptyLinesAroundMethodBody:
# Style/EmptyLinesAroundModuleBody:
# Style/EmptyLiteral:
# Style/EndBlock:
# Style/EndOfLine:
# Style/EvenOdd:
# Style/ExtraSpacing:
# Style/FileName:
# Style/FirstMethodParameterLineBreak:
# Style/FlipFlop:
# Style/For:
# Style/FormatString:
Style/FrozenStringLiteralComment:
  Enabled: false
# Style/GlobalVars:
# Style/GuardClause:
# Style/HashSyntax:
# Style/IdenticalConditionalBranches:
# Style/IfInsideElse:
# Style/IfUnlessModifier:
# Style/IfWithSemicolon:
# Style/IndentArray:
# Style/IndentAssignment:
# Style/IndentationConsistency:
# Style/IndentationWidth:
# Style/IndentHash:
# Style/InfiniteLoop:
# Style/Lambda:
# Style/LambdaCall:
# Style/LeadingCommentSpace:
# Style/LineEndConcatenation:
# Style/MethodCallParentheses:
# Style/MethodDefParentheses:
# Style/MethodName:
# Style/ModuleFunction:
# Style/MultilineArrayBraceLayout:
# Style/MultilineBlockChain:
# Style/MultilineBlockLayout:
# Style/MultilineHashBraceLayout:
# Style/MultilineIfThen:
# Style/MultilineMethodCallBraceLayout:
# Style/MultilineMethodCallIndentation:
# Style/MultilineMethodDefinitionBraceLayout:
# Style/MultilineOperationIndentation:
# Style/MultilineTernaryOperator:
# Style/MutableConstant:
# Style/NegatedIf:
# Style/NegatedWhile:
# Style/NestedModifier:
# Style/NestedParenthesizedCalls:
# Style/NestedTernaryOperator:
# Style/Next:
# Style/NilComparison:
# Style/NonNilCheck:
# Style/Not:
# Style/NumericLiterals:
# Style/OneLineConditional:
# Style/OpMethod:
# Style/ParallelAssignment:
# Style/ParenthesesAroundCondition:
# Style/PercentLiteralDelimiters:
# Style/PercentQLiterals:
# Style/PerlBackrefs:
# Style/PredicateName:
# Style/Proc:
# Style/RaiseArgs:
# Style/RedundantBegin:
# Style/RedundantException:
# Style/RedundantFreeze:
# Style/RedundantParentheses:
# Style/RedundantReturn:
# Style/RedundantSelf:
# Style/RegexpLiteral:
# Style/RescueModifier:
# Style/SelfAssignment:
# Style/Semicolon:
# Style/SignalException:
# Style/SingleLineBlockParams:
# Style/SingleLineMethods:
# Style/SpaceAfterColon:
# Style/SpaceAfterComma:
# Style/SpaceAfterMethodName:
# Style/SpaceAfterNot:
# Style/SpaceAfterSemicolon:
# Style/SpaceAroundEqualsInParameterDefault:
# Style/SpaceAroundKeyword:
# Style/SpaceAroundOperators:
# Style/SpaceBeforeBlockBraces:
# Style/SpaceBeforeComma:
# Style/SpaceBeforeComment:
# Style/SpaceBeforeFirstArg:
# Style/SpaceBeforeSemicolon:
# Style/SpaceInsideBlockBraces:
# Style/SpaceInsideBrackets:
# Style/SpaceInsideHashLiteralBraces:
# Style/SpaceInsideParens:
# Style/SpaceInsideRangeLiteral:
# Style/SpaceInsideStringInterpolation:
# Style/SpecialGlobalVars:
# Style/StabbyLambdaParentheses:
# Style/StringLiterals:
# Style/StringLiteralsInInterpolation:
# Style/StringMethods:
# Style/SymbolArray:
# Style/SymbolProc:
# Style/Tab:
# Style/TrailingBlankLines:
# Style/TrailingCommaInArguments:
# Style/TrailingCommaInLiteral:
# Style/TrailingUnderscoreVariable:
# Style/TrailingWhitespace:
# Style/TrivialAccessors:
# Style/UnlessElse:
# Style/UnneededCapitalW:
# Style/UnneededInterpolation:
# Style/UnneededPercentQ:
# Style/VariableInterpolation:
# Style/VariableName:
# Style/WhenThen:
# Style/WhileUntilDo:
# Style/WhileUntilModifier:
# Style/WordArray:
# Style/ZeroLengthPredicate:
